// <auto-generated />
using System;
using FinalProjectAPIBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectAPIBackend.Migrations
{
    [DbContext(typeof(FinalProjectAPIBackendDbContext))]
    [Migration("20240624194811_MinorFixes")]
    partial class MinorFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVENTS_PERFORMERS", b =>
                {
                    b.Property<int>("EventsEventId")
                        .HasColumnType("int");

                    b.Property<int>("PerformersPerformerId")
                        .HasColumnType("int");

                    b.HasKey("EventsEventId", "PerformersPerformerId");

                    b.HasIndex("PerformersPerformerId");

                    b.ToTable("EVENTS_PERFORMERS");
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EVENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("EVENT_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("IMAGE_URL");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TITLE");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId");

                    b.ToTable("EVENTS", (string)null);
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.EventSave", b =>
                {
                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("SaveId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EventId")
                        .HasName("SAVE_ID");

                    b.HasIndex("EventId");

                    b.ToTable("EVENT_SAVES", (string)null);
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.Performer", b =>
                {
                    b.Property<int>("PerformerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PERFORMER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("PerformerId");

                    b.HasIndex(new[] { "Name" }, "IX_PERFORMER");

                    b.ToTable("PERFORMERS", (string)null);
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_ROLE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_EMAIL")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ_USERNAME")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VENUE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<int>("VenueAddressId")
                        .HasColumnType("int");

                    b.HasKey("VenueId");

                    b.HasIndex("VenueAddressId")
                        .IsUnique();

                    b.ToTable("VENUES", (string)null);
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.VenueAddress", b =>
                {
                    b.Property<int>("VenueAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("V_ADDRESS_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueAddressId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CITY");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STREET");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("STREET_NUMBER");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZIP_CODE");

                    b.HasKey("VenueAddressId");

                    b.ToTable("VENUE_ADDRESSES", (string)null);
                });

            modelBuilder.Entity("EVENTS_PERFORMERS", b =>
                {
                    b.HasOne("FinalProjectAPIBackend.Data.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectAPIBackend.Data.Performer", null)
                        .WithMany()
                        .HasForeignKey("PerformersPerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.Event", b =>
                {
                    b.HasOne("FinalProjectAPIBackend.Data.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinalProjectAPIBackend.Data.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_VENUE_EVENTS");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.EventSave", b =>
                {
                    b.HasOne("FinalProjectAPIBackend.Data.Event", "Event")
                        .WithMany("EventSaves")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectAPIBackend.Data.User", "User")
                        .WithMany("EventSaves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.Venue", b =>
                {
                    b.HasOne("FinalProjectAPIBackend.Data.VenueAddress", "VenueAddress")
                        .WithOne("Venue")
                        .HasForeignKey("FinalProjectAPIBackend.Data.Venue", "VenueAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VENUE_ADDRESS");

                    b.Navigation("VenueAddress");
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.Event", b =>
                {
                    b.Navigation("EventSaves");
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.User", b =>
                {
                    b.Navigation("EventSaves");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.Venue", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("FinalProjectAPIBackend.Data.VenueAddress", b =>
                {
                    b.Navigation("Venue");
                });
#pragma warning restore 612, 618
        }
    }
}
